name: 'Frank Manley & Associates'
favicon: null
layout_spectrum: 0.07002
typography_spectrum: 0.36783689307048917
title: Real Estate Real Smart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0c'
    - '#ffffff'
    - '#cdcabc'
    - '#00eaff'
    - '#484933'
  brandStrength: 0.625
  lightness: 0.2629642409738153
  saturation: 0.1316304998472333
  rhythmicContrast: 0.25
purpose: []
