name: 'Frank Manley & Associates'
favicon: null
layout_spectrum: 0.32044
typography_spectrum: 0.36783689307048917
title: Keller Williams Capital Properties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5cbbff'
    - '#0e0e0c'
    - '#ffb3a4'
    - '#a1874f'
  brandStrength: 0.625
  lightness: 0.2629642409738153
  saturation: 0.1316304998472333
  rhythmicContrast: 0.5
purpose: []
