name: 'Frank Manley & Associates'
favicon: null
layout_spectrum: 0.8847087379544973
typography_spectrum: 0.36783689307048917
title: Real Estate Real Smart
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5744771407917142
  lightness: 0.2629642409738153
  saturation: 0.1316304998472333
  rhythmicContrast: 0.20788464765064418
purpose: []
